# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Proximite
                                 A QGIS plugin
 Affiche les éléments à une distance définissable d'un élément de base
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-02-08
        copyright            : (C) 2023 by Matthieu Ahr
        email                : matthieu.ahr@ensg.eu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Proximite class from file Proximite.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .proximite import Proximite
    return Proximite(iface)
